### ISSUE TITLE
Bug: iOS: Preview panel showing up for PDF instead of the "Share" modal

### ISSUE THREAD

**Issue by davidmarquis** [moberwasserlechner/capacitor-filesharer#21] opened 2020-07-02 20:23 UTC
### Capacitor version:

```
Latest Dependencies:

  @capacitor/cli: 2.2.1

  @capacitor/core: 2.2.1

  @capacitor/android: 2.2.1

  @capacitor/electron: 2.2.1

  @capacitor/ios: 2.2.1

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.0.2

  @capacitor/android 2.0.2

  @capacitor/ios 2.0.2

  @capacitor/core 2.0.2

[success] Android looking great! 👌
  Found 5 Capacitor plugins for ios:
    @byteowls/capacitor-filesharer (2.0.0)
    cordova-plugin-actionsheet (2.3.3)
    cordova-plugin-badge (0.8.8)
    cordova-plugin-dialogs (2.0.2)
    uk.co.workingedge.phonegap.plugin.launchnavigator (5.0.4)
[success] iOS looking great! 👌

```

### Library version:

- 2.0.0

### Your Plugin Configuration
```typescript
FileSharer.share({
          filename: file.name,     // contains "invoice_0002.pdf"
          base64Data: base64,   // verified that this contains valid base64 encoded data
          contentType: file.type, // contains "application/pdf"
        }).catch(error => {
          console.error('File sharing failed', error.message);
        });
```

### Affected Platform(s):

- iOS

### Current Behavior
When I invoke the plugin, the PDF file gets displayed in some sort of PDF preview UI instead of the Share activity modal.
The PDF renders as expected, which means the data itself is OK but somehow there's no Share modal at all and there's also no way to close that preview panel.

### Expected Behavior
I would have expected the Share modal to be displayed as such: https://youtu.be/p7f6yamZxCk?t=762

### Sample Code or Sample Application Repo
See above.

### Other Information
The iOS logs are only showing this:

```
WebView loaded
```

**Comment by davidmarquis** [comment] 2020-07-02 20:29
Here's a screenshot of the preview panel that shows up:

![image](https://user-images.githubusercontent.com/393893/86406499-338e7a80-bc81-11ea-809f-904f353144ad.png)

**Comment by moberwasserlechner** [comment] 2020-09-18 11:49
Hi, 

I tested it with iOS 13+ and it always works. What ios version do you use?

BR

**Comment by Rosadojonathan** [comment] 2020-10-02 08:35
Up! I'm having the exact same issue. I'm on iOS 14.0.1

**Comment by SayWhat69** [comment] 2020-11-21 12:54
I have the same bug with an png image.

**Comment by NikJaySix** [comment] 2020-11-29 23:31
Same issue here. Previews the PDF instead of opening the share options.

**Comment by kams2160** [comment] 2021-03-22 22:19
Same here for CSV data and iOS 14.4. I see only fullscreen preview with my CSV.

**Comment by FeoSilva** [comment] 2021-04-09 00:50
I fixed it installing the pods with the command `pod install` inside .xcodeproj folder

**Comment by zack1013** [comment] 2021-04-14 09:05
> I fixed it by installing the pods with the command `pod install` inside the .xcodeproj folder

may i have more detail how to fix that? thanks.

**Comment by FeoSilva** [comment] 2021-04-14 14:18
> > I fixed it by installing the pods with the command `pod install` inside the .xcodeproj folder
> 
> may i have more detail how to fix that? thanks.

After installed the dependency (`npm i @byteowls/capacitor-filesharer` or `yarn add @byteowls/capacitor-filesharer`), open the terminal in the folder where is .xcodeproject file and run the command `pod install`

**Comment by nik736** [comment] 2021-04-17 15:43
+1 I have the same issue with a jpg

**Comment by berkayyildiz** [comment] 2021-07-10 04:47
I had same problem, it fixed after `npx cap sync`.

**Comment by MajorPrime** [comment] 2021-07-26 21:28
We had this issue despite already using `cap sync`
For us, we had to register the plugin (in `index.tsx` where we call `ReactDOM.render`)
(cordova v2.4)

```
import {FileSharer} from '@byteowls/capacitor-filesharer';
import {registerWebPlugin} from '@capacitor/core';
registerWebPlugin(FileSharer);
```

**Comment by moberwasserlechner** [comment] 2021-09-23 16:13
I released the new version `3.0.0` today

If you can and it is still relevant please test this issue with the new version. (Capacitor 3.0.0 required)

I keep this issue open a few days and close it afterwards if there is no feedback.

BR Michael

**Comment by Hanho-Kim** [comment] 2022-03-27 07:11
I am currently developing on Capacitor 2.4 and it still has the same issue. I already tried the solutions above.

**Comment by Hanho-Kim** [comment] 2022-03-30 07:01
For those who are developing on capacitor 2.0,
```FileSharer.share({...})``` => Not working as intended. Some previewing webview is appeared without any failed/error message. (This should be fixed for preventing confusion)

```Plugins.FileSharer.share({...})``` => Working fine.

**Comment by moberwasserlechner** [comment] 2022-09-18 18:50
Closed as outdated.

**Closed by moberwasserlechner** 2022-09-18 18:50 UTC
Labels: wontfix, ios
