### ISSUE TITLE
The code skips whatever is written after ''Filereader.onloadend = "

### ISSUE THREAD

**Issue by pratiksan45** [moberwasserlechner/capacitor-filesharer#25] opened 2020-09-24 05:34 UTC
I am using Filesharer in my Ionic 5 app. But It is not working. 
I have used breakpoints in the code and found out that, the code is not able to reach after `Filereader.onloadend =() => {` and after. This is the reason I am not able to use the plugin in my app. 
Please help.

**Comment by KrishPro** [comment] 2020-12-19 18:30
I was having the same issue.
For me it solved by uninstalling all of the cordova plugins

In my case it was `cordova-plugin-file` only,
So I used capacitor's `FileSystem Plugin` instead of  `cordova-plugin-file`

Capacitor's Plugins don't require any installation they comes with `@capacitor/core`
Let me know if it works or not

**Comment by moberwasserlechner** [comment] 2021-09-23 16:13
I released the new version `3.0.0` today

If you can and it is still relevant please test this issue with the new version. (Capacitor 3.0.0 required)

I keep this issue open a few days and close it afterwards if there is no feedback.

BR Michael

**Comment by hrbmiguelromeroh** [comment] 2021-11-19 14:01
this is srill happening on build `3.0.0` for ionic 5, w/ cap ^3 @moberwasserlechner

**Comment by matadorhernan** [comment] 2022-02-02 22:11
the issue is conflicting with cordova-plugin-file

**Comment by KrishPro** [comment] 2022-02-03 04:34
> the issue this plugin is conflicting with cordova-plugin-file

This is a bug in this plugin, I was also having this same issue.

The solutions is to use Capacitor's Plugin
You can you us Capacitor's FileSystem Plugin for your usecase.

Note: For capacitor 3+ you'll have to install it with `npm install @capacitor/filesystem`

**Comment by moberwasserlechner** [comment] 2022-09-18 18:50
Closed as outdated.

**Closed by moberwasserlechner** 2022-09-18 18:50 UTC
Labels: web
